## from nextstrain meta get country and region

In [1]:
import pandas as pd

In [6]:
## seperate country from code nextstrain metadata 
df =pd.read_csv("spike_nextstrain_meta.csv")
df.head

<bound method NDFrame.head of           taxa_x  acession  version_x      taxa_y  version_y  \
0     KM349742.1  KM349742          1  KM349742.1          1
1     KM349743.1  KM349743          1  KM349743.1          1
2     KC875821.1  KC875821          1  KC875821.1          1
3     KC875821.1  KC875821          1  KC875821.1          1
4     KC875821.1  KC875821          1  KC875821.1          1
...          ...       ...        ...         ...        ...
1529  JQ065049.1  JQ065049          1  JQ065049.1          1
1530  JQ065048.1  JQ065048          1  JQ065048.1          1
1531  JQ065047.1  JQ065047          1  JQ065047.1          1
1532  JQ065046.1  JQ065046          1  JQ065046.1          1
1533  JQ065042.2  JQ065042          2  JQ065042.2          2

              Release_Date                                            Species  \
0     2015-01-04T00:00:00Z                     China Rattus coronavirus HKU24
1     2015-01-04T00:00:00Z                     China Rattus coronavirus HKU24
2     2013-06-23T00:00:00Z  Middle East respiratory syndrome-related coron...
3     2013-06-23T00:00:00Z  Middle East respiratory syndrome-related coron...
4     2013-06-23T00:00:00Z  Middle East respiratory syndrome-related coron...
...                    ...                                                ...
1529               3/19/12                                         HKU19-6918
1530               3/19/12                                         HKU20-9243
1531               3/19/12                                         HKU21-8295
1532               5/13/16                                           HKU15-44
1533               5/13/16                                          HKU15-155

                                           Species_code         Family  \
0                        China Rattus coronavirus HKU24  Coronaviridae
1                        China Rattus coronavirus HKU24  Coronaviridae
2     Middle East respiratory syndrome-related coron...  Coronaviridae
3     Middle East respiratory syndrome-related coron...  Coronaviridae
4     Middle East respiratory syndrome-related coron...  Coronaviridae
...                                                 ...            ...
1529                                              HKU19  Coronaviridae
1530                                              HKU20  Coronaviridae
1531                                              HKU21  Coronaviridae
1532                                           HKU15-44  Coronaviridae
1533                                              HKU15  Coronaviridae

       Length Nuc_Completeness  \
0     31249.0         complete
1     31249.0         complete
2      5130.0          partial
3      5130.0          partial
4      5130.0          partial
...       ...              ...
1529  26077.0              NaN
1530  26227.0              NaN
1531  26223.0              NaN
1532  25430.0              NaN
1533  25425.0              NaN

                                                Authors Publications  \
0     Lau,S.K., Woo,P.C., Li,K.S., Tsang,A.K., Fan,R...     25552712
1     Lau,S.K., Woo,P.C., Li,K.S., Tsang,A.K., Fan,R...     25552712
2     Drosten,C., Seilmaier,M., Corman,V.M., Hartman...     23782859
3     Drosten,C., Seilmaier,M., Corman,V.M., Hartman...     23782859
4     Drosten,C., Seilmaier,M., Corman,V.M., Hartman...     23782859
...                                                 ...          ...
1529                                                NaN          NaN
1530                                                NaN          NaN
1531                                                NaN          NaN
1532                                                NaN          NaN
1533                                                NaN          NaN

          Geo_Location               Host Isolation_Source Collection_Date  \
0                China  Rattus norvegicus              NaN         5/17/12
1                China  Rattus norvegicus              NaN         5/17/12
2                Qatar       Homo sapiens             lung            2012
3                Qatar       Homo sapiens             lung            2012
4                Qatar       Homo sapiens             lung            2012
...                ...                ...              ...             ...
1529  China: Hong Kong        night-heron              NaN            2007
1530  China: Hong Kong             wigeon              NaN            2008
1531  China: Hong Kong     common moorhen              NaN            2007
1532  China: Hong Kong                pig              NaN            2009
1533  China: Hong Kong                pig              NaN            2010

     collection_date_code                                      GenBank_Title  \
0                 5/17/12  Betacoronavirus HKU24 strain HKU24-R05005I, co...
1                 5/17/12  Betacoronavirus HKU24 strain HKU24-R05009I, co...
2                 7/15/12  Human betacoronavirus 2c EMC/2012 strain Essen...
3                 7/15/12  Human betacoronavirus 2c EMC/2012 strain Essen...
4                 7/15/12  Human betacoronavirus 2c EMC/2012 strain Essen...
...                   ...                                                ...
1529              7/15/07                                         HKU19-6918
1530              7/15/08                                         HKU20-9243
1531              7/15/07                                         HKU21-8295
1532              7/15/09                                           HKU15-44
1533              7/15/10                                          HKU15-155

                                               taxa_new
0     KM349742|Betacoronavirus HKU24 strain HKU24-R0...
1     KM349743|Betacoronavirus HKU24 strain HKU24-R0...
2     KC875821|Human betacoronavirus 2c EMC/2012 str...
3     KC875821|Human betacoronavirus 2c EMC/2012 str...
4     KC875821|Human betacoronavirus 2c EMC/2012 str...
...                                                 ...
1529                                       JQ065049|nan
1530                                       JQ065048|nan
1531                                       JQ065047|nan
1532                                       JQ065046|nan
1533                                       JQ065042|nan

[1534 rows x 20 columns]>

In [7]:
df[['country','state']] = df.Geo_Location.str.split(":",expand=True)
df

,taxa_x,acession,version_x,taxa_y,version_y,Release_Date,Species,Species_code,Family,Length,...,Publications,Geo_Location,Host,Isolation_Source,Collection_Date,collection_date_code,GenBank_Title,taxa_new,country,state
0,KM349742.1,KM349742,1,KM349742.1,1,2015-01-04T00:00:00Z,China Rattus coronavirus HKU24,China Rattus coronavirus HKU24,Coronaviridae,31249.0,...,25552712,China,Rattus norvegicus,NaN,5/17/12,5/17/12,"Betacoronavirus HKU24 strain HKU24-R05005I, co...",KM349742|Betacoronavirus HKU24 strain HKU24-R0...,China,None
1,KM349743.1,KM349743,1,KM349743.1,1,2015-01-04T00:00:00Z,China Rattus coronavirus HKU24,China Rattus coronavirus HKU24,Coronaviridae,31249.0,...,25552712,China,Rattus norvegicus,NaN,5/17/12,5/17/12,"Betacoronavirus HKU24 strain HKU24-R05009I, co...",KM349743|Betacoronavirus HKU24 strain HKU24-R0...,China,None
2,KC875821.1,KC875821,1,KC875821.1,1,2013-06-23T00:00:00Z,Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,Coronaviridae,5130.0,...,23782859,Qatar,Homo sapiens,lung,2012,7/15/12,Human betacoronavirus 2c EMC/2012 strain Essen...,KC875821|Human betacoronavirus 2c EMC/2012 str...,Qatar,None
3,KC875821.1,KC875821,1,KC875821.1,1,2013-06-23T00:00:00Z,Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,Coronaviridae,5130.0,...,23782859,Qatar,Homo sapiens,lung,2012,7/15/12,Human betacoronavirus 2c EMC/2012 strain Essen...,KC875821|Human betacoronavirus 2c EMC/2012 str...,Qatar,None
4,KC875821.1,KC875821,1,KC875821.1,1,2013-06-23T00:00:00Z,Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,Coronaviridae,5130.0,...,23782859,Qatar,Homo sapiens,lung,2012,7/15/12,Human betacoronavirus 2c EMC/2012 strain Essen...,KC875821|Human betacoronavirus 2c EMC/2012 str...,Qatar,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,JQ065049.1,JQ065049,1,JQ065049.1,1,3/19/12,HKU19-6918,HKU19,Coronaviridae,26077.0,...,NaN,China: Hong Kong,night-heron,NaN,2007,7/15/07,HKU19-6918,JQ065049|nan,China,Hong Kong
1530,JQ065048.1,JQ065048,1,JQ065048.1,1,3/19/12,HKU20-9243,HKU20,Coronaviridae,26227.0,...,NaN,China: Hong Kong,wigeon,NaN,2008,7/15/08,HKU20-9243,JQ065048|nan,China,Hong Kong
1531,JQ065047.1,JQ065047,1,JQ065047.1,1,3/19/12,HKU21-8295,HKU21,Coronaviridae,26223.0,...,NaN,China: Hong Kong,common moorhen,NaN,2007,7/15/07,HKU21-8295,JQ065047|nan,China,Hong Kong
1532,JQ065046.1,JQ065046,1,JQ065046.1,1,5/13/16,HKU15-44,HKU15-44,Coronaviridae,25430.0,...,NaN,China: Hong Kong,pig,NaN,2009,7/15/09,HKU15-44,JQ065046|nan,China,Hong Kong
1533,JQ065042.2,JQ065042,2,JQ065042.2,2,5/13/16,HKU15-155,HKU15,Coronaviridae,25425.0,...,NaN,China: Hong Kong,pig,NaN,2010,7/15/10,HKU15-155,JQ065042|nan,China,Hong Kong

In [8]:

# import the dictionary 
dic=pd.read_csv("country-code.csv",index_col=0, squeeze=True).to_dict()

## do translate
df['region']=df['country'].map(dic)
df

,taxa_x,acession,version_x,taxa_y,version_y,Release_Date,Species,Species_code,Family,Length,...,Geo_Location,Host,Isolation_Source,Collection_Date,collection_date_code,GenBank_Title,taxa_new,country,state,region
0,KM349742.1,KM349742,1,KM349742.1,1,2015-01-04T00:00:00Z,China Rattus coronavirus HKU24,China Rattus coronavirus HKU24,Coronaviridae,31249.0,...,China,Rattus norvegicus,NaN,5/17/12,5/17/12,"Betacoronavirus HKU24 strain HKU24-R05005I, co...",KM349742|Betacoronavirus HKU24 strain HKU24-R0...,China,None,WPRO
1,KM349743.1,KM349743,1,KM349743.1,1,2015-01-04T00:00:00Z,China Rattus coronavirus HKU24,China Rattus coronavirus HKU24,Coronaviridae,31249.0,...,China,Rattus norvegicus,NaN,5/17/12,5/17/12,"Betacoronavirus HKU24 strain HKU24-R05009I, co...",KM349743|Betacoronavirus HKU24 strain HKU24-R0...,China,None,WPRO
2,KC875821.1,KC875821,1,KC875821.1,1,2013-06-23T00:00:00Z,Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,Coronaviridae,5130.0,...,Qatar,Homo sapiens,lung,2012,7/15/12,Human betacoronavirus 2c EMC/2012 strain Essen...,KC875821|Human betacoronavirus 2c EMC/2012 str...,Qatar,None,EMRO
3,KC875821.1,KC875821,1,KC875821.1,1,2013-06-23T00:00:00Z,Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,Coronaviridae,5130.0,...,Qatar,Homo sapiens,lung,2012,7/15/12,Human betacoronavirus 2c EMC/2012 strain Essen...,KC875821|Human betacoronavirus 2c EMC/2012 str...,Qatar,None,EMRO
4,KC875821.1,KC875821,1,KC875821.1,1,2013-06-23T00:00:00Z,Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,Coronaviridae,5130.0,...,Qatar,Homo sapiens,lung,2012,7/15/12,Human betacoronavirus 2c EMC/2012 strain Essen...,KC875821|Human betacoronavirus 2c EMC/2012 str...,Qatar,None,EMRO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1529,JQ065049.1,JQ065049,1,JQ065049.1,1,3/19/12,HKU19-6918,HKU19,Coronaviridae,26077.0,...,China: Hong Kong,night-heron,NaN,2007,7/15/07,HKU19-6918,JQ065049|nan,China,Hong Kong,WPRO
1530,JQ065048.1,JQ065048,1,JQ065048.1,1,3/19/12,HKU20-9243,HKU20,Coronaviridae,26227.0,...,China: Hong Kong,wigeon,NaN,2008,7/15/08,HKU20-9243,JQ065048|nan,China,Hong Kong,WPRO
1531,JQ065047.1,JQ065047,1,JQ065047.1,1,3/19/12,HKU21-8295,HKU21,Coronaviridae,26223.0,...,China: Hong Kong,common moorhen,NaN,2007,7/15/07,HKU21-8295,JQ065047|nan,China,Hong Kong,WPRO
1532,JQ065046.1,JQ065046,1,JQ065046.1,1,5/13/16,HKU15-44,HKU15-44,Coronaviridae,25430.0,...,China: Hong Kong,pig,NaN,2009,7/15/09,HKU15-44,JQ065046|nan,China,Hong Kong,WPRO
1533,JQ065042.2,JQ065042,2,JQ065042.2,2,5/13/16,HKU15-155,HKU15,Coronaviridae,25425.0,...,China: Hong Kong,pig,NaN,2010,7/15/10,HKU15-155,JQ065042|nan,China,Hong Kong,WPRO

In [9]:
df.to_csv("spike_nextstrain_meta2.csv", index=False)

## further furter the sequence by length , at least 60% length as SARS-CoV2 spike gene?

In [10]:

from Bio import SeqIO