In [1]:
from opencage.geocoder import OpenCageGeocode
import pandas as pd

In [2]:
##https://amaral.northwestern.edu/blog/getting-long-lat-list-cities
key = "8b122541ef634725a55728b9d265e5c7" # get api key from:  https://opencagedata.com
geocoder = OpenCageGeocode(key)

In [3]:
## test
query = 'Catham,GA' 
results = geocoder.geocode(query)
print (results)

[{'annotations': {'DMS': {'lat': "32Â° 45' 1.51200'' N", 'lng': "83Â° 30' 0.64800'' W"}, 'FIPS': {'state': '13'}, 'MGRS': '17SKS6575726384', 'Maidenhead': 'EM82fs90xc', 'Mercator': {'x': -9295197.519, 'y': 3839109.339}, 'OSM': {'note_url': 'https://www.openstreetmap.org/note/new#map=16/32.75042/-83.50018&layers=N', 'url': 'https://www.openstreetmap.org/?mlat=32.75042&mlon=-83.50018#map=16/32.75042/-83.50018'}, 'UN_M49': {'regions': {'AMERICAS': '019', 'NORTHERN_AMERICA': '021', 'US': '840', 'WORLD': '001'}, 'statistical_groupings': ['MEDC']}, 'callingcode': 1, 'currency': {'alternate_symbols': ['US$'], 'decimal_mark': '.', 'disambiguate_symbol': 'US$', 'html_entity': '$', 'iso_code': 'USD', 'iso_numeric': '840', 'name': 'United States Dollar', 'smallest_denomination': 1, 'subunit': 'Cent', 'subunit_to_unit': 100, 'symbol': '$', 'symbol_first': 1, 'thousands_separator': ','}, 'flag': 'ðŸ‡ºðŸ‡¸', 'geohash': 'djud7fj10bc1432g5c3e', 'qibla': 53.11, 'roadinfo': {'drive_on': 'right', 'speed_in': 'mph'}, 'sun': {'rise': {'apparent': 1622111400, 'astronomical': 1622105460, 'civil': 1622109720, 'nautical': 1622107680}, 'set': {'apparent': 1622075580, 'astronomical': 1622081520, 'civil': 1622077260, 'nautical': 1622079300}}, 'timezone': {'name': 'America/New_York', 'now_in_dst': 1, 'offset_sec': -14400, 'offset_string': '-0400', 'short_name': 'EDT'}, 'what3words': {'words': 'kangaroo.princes.waterfalls'}}, 'bounds': {'northeast': {'lat': 35.000659, 'lng': -80.751429}, 'southwest': {'lat': 30.355757, 'lng': -85.605165}}, 'components': {'ISO_3166-1_alpha-2': 'US', 'ISO_3166-1_alpha-3': 'USA', '_category': 'place', '_type': 'state', 'continent': 'North America', 'country': 'United States of America', 'country_code': 'us', 'state': 'Georgia', 'state_code': 'GA'}, 'confidence': 1, 'formatted': 'Georgia, United States of America', 'geometry': {'lat': 32.75042, 'lng': -83.50018}}]

In [17]:
metadata=pd.read_csv("TX/nextstrain/data/metadata.tsv",sep= "\t")
meta=metadata.groupby(['location']).count()
meta = meta.reset_index()
meta['state'] = 'TX'
meta = meta[["location", "state"]]
meta

     location state
0     Aransas    TX
1    Atascosa    TX
2      Bailey    TX
3      Belton    TX
4       Bexar    TX
5      Brazos    TX
6   Calcasieu    TX
7     Cameron    TX
8        Camp    TX
9    Cherokee    TX
10     Collin    TX
11     Dallas    TX
12  DeafSmith    TX
13     Dimmit    TX
14      Ector    TX
15     ElPaso    TX
16      Falls    TX
17   FortBend    TX
18  Galveston    TX
19      Gregg    TX
20     Harris    TX
21    Hockley    TX
22    Houston    TX
23  Jefferson    TX
24    Johnson    TX
25    Leander    TX
26        Lee    TX
27    Lubbock    TX
28     Marlin    TX
29     Nueces    TX
30  Ochiltree    TX
31     Panola    TX
32  RoundRock    TX
33    Tarrant    TX
34     Taylor    TX
35     Temple    TX
36     Travis    TX
37       Waco    TX
38       Webb    TX
39       West    TX
40    Willacy    TX
41     lavaca    TX
42     parker    TX

In [18]:
list_lat = []   # create empty lists
list_long = []
for index, row in meta.iterrows(): # iterate over rows in dataframe

    City = row['location']
    State = row['state']       
    query = str(City)+','+str(State)

    results = geocoder.geocode(query)   
    lat = results[0]['geometry']['lat']
    long = results[0]['geometry']['lng']

    list_lat.append(lat)
    list_long.append(long)

# create new columns from lists    

meta['lat'] = list_lat   

meta['lon'] = list_long

In [19]:
meta

     location state        lat         lon
0     Aransas    TX  28.198788  -96.947708
1    Atascosa    TX  28.855443  -98.531631
2      Bailey    TX  34.034919 -102.814937
3      Belton    TX  31.056013  -97.464453
4       Bexar    TX  29.426399  -98.510478
5      Brazos    TX  30.652313  -96.380580
6   Calcasieu    TX  32.240407  -95.368387
7     Cameron    TX  26.129119  -97.413428
8        Camp    TX  32.972313  -94.985286
9    Cherokee    TX  31.839083  -95.179185
10     Collin    TX  33.160963  -96.606098
11     Dallas    TX  32.776272  -96.796856
12  DeafSmith    TX  31.250440  -99.250610
13     Dimmit    TX  28.382195  -99.717823
14      Ector    TX  31.894175 -102.579434
15     ElPaso    TX  29.825377  -97.812956
16      Falls    TX  31.232094  -96.926213
17   FortBend    TX  31.250440  -99.250610
18  Galveston    TX  29.299328  -94.794588
19      Gregg    TX  32.449241  -94.853285
20     Harris    TX  29.811977  -95.374125
21    Hockley    TX  32.010851  -97.130374
22    Houston    TX  29.758938  -95.367697
23  Jefferson    TX  29.834772  -94.170450
24    Johnson    TX  32.376607  -97.356862
25    Leander    TX  30.558605  -97.844436
26        Lee    TX  30.303135  -96.958859
27    Lubbock    TX  33.563521 -101.879336
28     Marlin    TX  31.307602  -96.892353
29     Nueces    TX  27.715377  -97.619994
30  Ochiltree    TX  36.255922 -100.813815
31     Panola    TX  32.136771  -94.313007
32  RoundRock    TX  33.179524  -96.657032
33    Tarrant    TX  32.751366  -97.335696
34     Taylor    TX  32.279312  -99.881261
35     Temple    TX  31.098207  -97.342785
36     Travis    TX  30.287857  -97.756139
37       Waco    TX  31.549333  -97.146670
38       Webb    TX  27.698362  -99.252358
39       West    TX  31.803481  -97.093347
40    Willacy    TX  26.455395  -97.594748
41     lavaca    TX  29.370333  -96.933453
42     parker    TX  32.759948  -97.793577

In [20]:
meta.to_csv("TX/nextstrain/config/lat_longs.csv")